// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu0wSx2sQTle-BAp_gdeexNafDBRQNwx4',
    appId: '1:23484747271:web:2d864deb537f166ba7a4a2',
    messagingSenderId: '23484747271',
    projectId: 'book-buddies-c9ea1',
    authDomain: 'book-buddies-c9ea1.firebaseapp.com',
    storageBucket: 'book-buddies-c9ea1.appspot.com',
    measurementId: 'G-T4W6M4PFL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABpk9W9AfMKDS1wrvJwvHNOVEEDxDag-8',
    appId: '1:23484747271:android:31166d2a352b8009a7a4a2',
    messagingSenderId: '23484747271',
    projectId: 'book-buddies-c9ea1',
    storageBucket: 'book-buddies-c9ea1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpt2cl6aMPXAX-2d-je8cJBaTBMZmpTs',
    appId: '1:23484747271:ios:7e3dd70407875dbea7a4a2',
    messagingSenderId: '23484747271',
    projectId: 'book-buddies-c9ea1',
    storageBucket: 'book-buddies-c9ea1.appspot.com',
    androidClientId: '23484747271-v7j83on3g485v65u0s6j8cieg1r255hn.apps.googleusercontent.com',
    iosClientId: '23484747271-p2lmpu00rddcjidrl2ga83g52ho3kedt.apps.googleusercontent.com',
    iosBundleId: 'br.com.bookbuddies',
  );
}
